// FILE: apps/dashboard/app/problems/page.tsx
'use client'
import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import Layout from '../../components/Layout'
import DataTable from '../../components/DataTable'
import StatusBadge from '../../components/StatusBadge'
import { acknowledgeProb,getHosts,getProblems,resolveProb } from '../../lib/api'
import { formatDuration } from '../../lib/format'
export default function Problems(){const[tab,setTab]=useState('active'),[severity,setSeverity]=useState(''),[host,setHost]=useState(''),[search,setSearch]=useState(''),[problems,setProblems]=useState<any[]>([]),[hosts,setHosts]=useState<any[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Record<string,boolean>>({});async function load(){setLoading(true);const q=new URLSearchParams();q.set('status',tab);if(severity)q.set('severity',severity);if(host)q.set('host_id',host);const r=await getProblems(`?${q}`);setProblems(r.problems||[]);setLoading(false)}useEffect(()=>{getHosts().then(r=>setHosts(r.hosts||[]));load();const t=setInterval(load,15000);return()=>clearInterval(t)},[tab,severity,host]);const rows=useMemo(()=>problems.filter(p=>!search||`${p.hostname} ${p.title}`.toLowerCase().includes(search.toLowerCase())),[problems,search]);async function bulkAck(){for(const id of Object.keys(selected).filter(k=>selected[k])) await acknowledgeProb(id);setSelected({});load()}return <Layout title="Problems" breadcrumbs={['Monitoring','Problems']} actions={[{label:'Refresh',onClick:load},{label:'Bulk acknowledge',onClick:bulkAck}]}><div style={{marginBottom:10}}>{['active','acknowledged','resolved'].map(t=><button className="btn" key={t} style={{background:tab===t?'#e8f0fe':'#fff'}} onClick={()=>setTab(t)}>{t} ({t===tab?rows.length:''})</button>)}</div><div className="panel" style={{padding:10,marginBottom:10,display:'flex',gap:8}}><select className="field" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option><option>warning</option><option>critical</option></select><select className="field" value={host} onChange={e=>setHost(e.target.value)}><option value="">All hosts</option>{hosts.map(h=><option key={h.id} value={h.id}>{h.hostname}</option>)}</select><input className="field" placeholder="Search" value={search} onChange={e=>setSearch(e.target.value)}/><b>{rows.length} {tab} problems</b></div><DataTable loading={loading} data={rows} columns={[{key:'sel',header:'',render:r=><input type="checkbox" checked={!!selected[r.id]} onChange={e=>setSelected({...selected,[r.id]:e.target.checked})}/>},{key:'severity',header:'Severity',render:r=><StatusBadge status={r.severity}/>},{key:'hostname',header:'Host',render:r=><Link href={`/hosts/${r.host_id}`}>{r.hostname}</Link>},{key:'title',header:'Problem'},{key:'metric_name',header:'Metric'},{key:'trigger_value',header:'Value'},{key:'duration_ms',header:'Duration',render:r=>formatDuration(Number(r.duration_ms||0))},{key:'actions',header:'Actions',render:r=><><button className="btn" disabled={r.status!=='active'} onClick={async()=>{await acknowledgeProb(r.id);load()}}>Acknowledge</button> <button className="btn" disabled={r.status==='resolved'} onClick={async()=>{await resolveProb(r.id);load()}}>Resolve</button> <Link href={`/hosts/${r.host_id}`}>View Host</Link></>}]} emptyMessage="No active problems"/></Layout>}
