// FILE: apps/dashboard/app/host-groups/page.tsx
'use client'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import Layout from '../../components/Layout'
import DataTable from '../../components/DataTable'
import { createHostGroup,deleteHostGroup,getHostGroups,updateHostGroup } from '../../lib/api'
export default function HostGroups(){const[groups,setGroups]=useState<any[]>([]),[show,setShow]=useState(false),[edit,setEdit]=useState<any>(null),[form,setForm]=useState({name:'',description:''});async function load(){const r=await getHostGroups();setGroups(r.groups||[])}useEffect(()=>{load()},[]);function open(g?:any){setEdit(g||null);setForm(g?{name:g.name,description:g.description||''}:{name:'',description:''});setShow(true)}async function save(e:any){e.preventDefault();edit?await updateHostGroup(edit.id,form):await createHostGroup(form);setShow(false);load()}return <Layout title="Host Groups" breadcrumbs={['Monitoring','Host Groups']} actions={[{label:'Create Group',onClick:()=>open(),primary:true}]}><DataTable data={groups} columns={[{key:'name',header:'Name',render:r=><Link href={`/hosts?group=${r.id}`}>{r.name}</Link>},{key:'description',header:'Description'},{key:'host_count',header:'Host Count'},{key:'created_at',header:'Created',render:r=>new Date(r.created_at).toLocaleString()},{key:'actions',header:'Actions',render:r=><><button className="btn" onClick={()=>open(r)}>Edit</button> <button className="btn" disabled={r.host_count>0} title={r.host_count>0?'Cannot delete group with hosts':''} onClick={async()=>{if(r.host_count>0)return alert('Delete disabled because group has hosts');await deleteHostGroup(r.id);load()}}>Delete</button></>}]} emptyMessage="No host groups"/>{show&&<div style={overlay}><form className="panel" style={modal} onSubmit={save}><h2>{edit?'Edit':'Create'} Group</h2><input required className="field" placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="field" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div><button className="btn btn-primary">Save</button> <button type="button" className="btn" onClick={()=>setShow(false)}>Cancel</button></div></form></div>}</Layout>}
const overlay={position:'fixed' as any,inset:0,background:'rgba(0,0,0,.25)',display:'grid',placeItems:'center',zIndex:20};const modal={width:400,padding:16,display:'grid',gap:8}
