// FILE: apps/dashboard/app/alert-history/page.tsx
'use client'
import { useEffect,useState } from 'react'
import Layout from '../../components/Layout'
import DataTable from '../../components/DataTable'
import StatusBadge from '../../components/StatusBadge'
import { getHosts,getProblems } from '../../lib/api'
import { formatDuration } from '../../lib/format'
export default function AlertHistory(){const[days,setDays]=useState(7),[host,setHost]=useState(''),[severity,setSeverity]=useState(''),[hosts,setHosts]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]);async function load(){const q=new URLSearchParams();q.set('status','resolved');q.set('limit','500');if(host)q.set('host_id',host);if(severity)q.set('severity',severity);const r=await getProblems(`?${q}`);setRows((r.problems||[]).filter((p:any)=>Date.now()-new Date(p.triggered_at).getTime()<=days*86400000))}useEffect(()=>{getHosts().then(r=>setHosts(r.hosts||[]));load()},[days,host,severity]);function csv(){const blob=new Blob([rows.map(r=>[r.severity,r.hostname,r.title,r.triggered_at,r.resolved_at].join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='alert-history.csv';a.click()}return <Layout title="Alert History" breadcrumbs={['Alerts','Alert History']} actions={[{label:'Export CSV',onClick:csv}]}><div className="panel" style={{padding:10,marginBottom:10,display:'flex',gap:8}}><select className="field" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><select className="field" value={host} onChange={e=>setHost(e.target.value)}><option value="">All hosts</option>{hosts.map(h=><option key={h.id} value={h.id}>{h.hostname}</option>)}</select><select className="field" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option><option>warning</option><option>critical</option></select></div><DataTable data={rows} columns={[{key:'severity',header:'Severity',render:r=><StatusBadge status={r.severity}/>},{key:'hostname',header:'Host'},{key:'title',header:'Problem'},{key:'triggered_at',header:'Triggered',render:r=>new Date(r.triggered_at).toLocaleString()},{key:'resolved_at',header:'Resolved',render:r=>r.resolved_at?new Date(r.resolved_at).toLocaleString():'-'},{key:'duration_ms',header:'Duration',render:r=>formatDuration(Number(r.duration_ms||0))},{key:'acknowledged_by',header:'Acknowledged By'}]} emptyMessage="No alert history"/></Layout>}
