// FILE: services/auth-api/src/routes/admin.routes.ts
import { FastifyInstance,FastifyRequest } from 'fastify'
import bcrypt from 'bcryptjs'
import { v4 as uuid } from 'uuid'
import { db } from '../db'
function tenant(req:FastifyRequest){return (req as any).user.tenant_id} function isAdmin(req:FastifyRequest){return (req as any).user.role==='admin'}
export default async function adminRoutes(fastify:FastifyInstance){fastify.addHook('preHandler',(fastify as any).authenticate)
 fastify.addHook('preHandler',async(req,reply)=>{if(req.url.startsWith('/admin')&&!isAdmin(req))return reply.code(403).send({error:'Admin role required'})})
 fastify.get('/admin/users',async(req,reply)=>{try{const r=await db.query('SELECT id,tenant_id,name,email,role,status,last_login_at,created_at FROM users WHERE tenant_id=$1 ORDER BY created_at DESC',[tenant(req)]);return{users:r.rows}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to list users'})}})
 fastify.post('/admin/users',async(req,reply)=>{try{const b:any=req.body||{};if(!b.email||!b.password)return reply.code(400).send({error:'email and password required'});const hash=await bcrypt.hash(b.password,12);const r=await db.query(`INSERT INTO users(id,tenant_id,name,email,password_hash,role,status,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,NOW()) RETURNING id,tenant_id,name,email,role,status,created_at`,[uuid(),tenant(req),b.name||b.email.split('@')[0],b.email,hash,b.role||'viewer',b.status||'active']);return reply.code(201).send({user:r.rows[0]})}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to create user'})}})
 fastify.put('/admin/users/:id',async(req,reply)=>{try{const b:any=req.body||{};const r=await db.query(`UPDATE users SET name=COALESCE($3,name),email=COALESCE($4,email),role=COALESCE($5,role),status=COALESCE($6,status) WHERE id=$1 AND tenant_id=$2 RETURNING id,tenant_id,name,email,role,status,last_login_at,created_at`,[(req.params as any).id,tenant(req),b.name,b.email,b.role,b.status]);if(!r.rows[0])return reply.code(404).send({error:'User not found'});return{user:r.rows[0]}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to update user'})}})
 fastify.delete('/admin/users/:id',async(req,reply)=>{try{await db.query('DELETE FROM users WHERE id=$1 AND tenant_id=$2',[(req.params as any).id,tenant(req)]);return{ok:true}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to delete user'})}})
 fastify.post('/admin/users/:id/reset-password',async(req,reply)=>{try{const b:any=req.body||{};if(!b.password||b.password.length<8)return reply.code(400).send({error:'password min 8 chars'});const hash=await bcrypt.hash(b.password,12);await db.query('UPDATE users SET password_hash=$3 WHERE id=$1 AND tenant_id=$2',[(req.params as any).id,tenant(req),hash]);return{ok:true}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to reset password'})}})
 fastify.get('/admin/audit',async(req,reply)=>{try{const q:any=req.query||{};const limit=Math.min(Number(q.limit||100),500),offset=Number(q.offset||0);const r=await db.query(`SELECT al.*,u.email user_email,u.name user_name FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id WHERE al.tenant_id=$1 ORDER BY al.created_at DESC LIMIT $2 OFFSET $3`,[tenant(req),limit,offset]);return{logs:r.rows}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to list audit logs'})}})
}
