// FILE: services/auth-api/src/routes/alertrules.routes.ts
import { FastifyInstance, FastifyRequest } from 'fastify'
import { v4 as uuid } from 'uuid'
import { db } from '../db'
function tenant(req:FastifyRequest){return (req as any).user.tenant_id}
export default async function alertRulesRoutes(fastify:FastifyInstance){fastify.addHook('preHandler',(fastify as any).authenticate)
 fastify.get('/alert-rules',async(req,reply)=>{try{const q:any=req.query||{};const p:any[]=[tenant(req)];let w='ar.tenant_id=$1';if(q.host_id){p.push(q.host_id);w+=` AND (ar.host_id=$${p.length} OR ar.host_id IS NULL)`}const r=await db.query(`SELECT ar.*,h.hostname,hg.name group_name FROM alert_rules ar LEFT JOIN hosts h ON h.id=ar.host_id LEFT JOIN host_groups hg ON hg.id=ar.host_group_id WHERE ${w} ORDER BY ar.name`,p);return{rules:r.rows}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to list alert rules'})}})
 fastify.post('/alert-rules',async(req,reply)=>{try{const b:any=req.body||{};if(!b.name||!b.metric_name)return reply.code(400).send({error:'name and metric_name are required'});const r=await db.query(`INSERT INTO alert_rules(id,tenant_id,host_id,host_group_id,name,metric_name,condition,warn_value,crit_value,duration_secs,is_enabled,notify_channels,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW()) RETURNING *`,[uuid(),tenant(req),b.host_id||null,b.host_group_id||null,b.name,b.metric_name,b.condition||'>',b.warn_value??null,b.crit_value??null,b.duration_secs||60,b.is_enabled!==false,b.notify_channels||[]]);return reply.code(201).send({rule:r.rows[0]})}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to create alert rule'})}})
 fastify.put('/alert-rules/:id',async(req,reply)=>{try{const b:any=req.body||{},id=(req.params as any).id;const cur=await db.query('SELECT * FROM alert_rules WHERE id=$1 AND tenant_id=$2',[id,tenant(req)]);if(!cur.rows[0])return reply.code(404).send({error:'Rule not found'});const c=cur.rows[0];const r=await db.query(`UPDATE alert_rules SET host_id=$3,host_group_id=$4,name=$5,metric_name=$6,condition=$7,warn_value=$8,crit_value=$9,duration_secs=$10,is_enabled=$11,notify_channels=$12 WHERE id=$1 AND tenant_id=$2 RETURNING *`,[id,tenant(req),b.host_id!==undefined?b.host_id:c.host_id,b.host_group_id!==undefined?b.host_group_id:c.host_group_id,b.name??c.name,b.metric_name??c.metric_name,b.condition??c.condition,b.warn_value!==undefined?b.warn_value:c.warn_value,b.crit_value!==undefined?b.crit_value:c.crit_value,b.duration_secs??c.duration_secs,b.is_enabled!==undefined?b.is_enabled:c.is_enabled,b.notify_channels??c.notify_channels]);return{rule:r.rows[0]}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to update alert rule'})}})
 fastify.delete('/alert-rules/:id',async(req,reply)=>{try{await db.query('DELETE FROM alert_rules WHERE id=$1 AND tenant_id=$2',[(req.params as any).id,tenant(req)]);return{ok:true}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to delete alert rule'})}})
 fastify.post('/alert-rules/:id/toggle',async(req,reply)=>{try{const r=await db.query('UPDATE alert_rules SET is_enabled=NOT is_enabled WHERE id=$1 AND tenant_id=$2 RETURNING *',[(req.params as any).id,tenant(req)]);if(!r.rows[0])return reply.code(404).send({error:'Rule not found'});return{rule:r.rows[0]}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to toggle alert rule'})}})
}
