// FILE: services/auth-api/src/routes/hosts.routes.ts
import { FastifyInstance, FastifyRequest } from 'fastify'
import { v4 as uuid } from 'uuid'
import { db, clickhouse } from '../db'

function tenant(req: FastifyRequest) { return (req as any).user.tenant_id }
function userId(req: FastifyRequest) { return (req as any).user.id || (req as any).user.user_id }
function agentKey() { return `ak_${uuid().replace(/-/g, '')}_${uuid().replace(/-/g, '').slice(0, 16)}` }
function rangeInterval(r: string) { return r === '1h' ? '1 hour' : r === '6h' ? '6 hours' : r === '7d' ? '7 days' : '24 hours' }
function sinceDays(d: number) { return `${Math.max(1, Math.min(90, d))} days` }
async function latestMetrics(hostId: string) {
  const res = await db.query(`SELECT DISTINCT ON (metric_name) metric_name,value,unit,collected_at FROM metric_values WHERE host_id=$1 ORDER BY metric_name,collected_at DESC`, [hostId])
  const m: any = {}; for (const r of res.rows) m[r.metric_name] = Number(r.value)
  if (m.ram_usage === undefined && m.ram_total_mb > 0) m.ram_usage = (m.ram_used_mb / m.ram_total_mb) * 100
  if (m.disk_usage === undefined && m.disk_total_gb > 0) m.disk_usage = (m.disk_used_gb / m.disk_total_gb) * 100
  if (m.net_in_mbps === undefined && m.net_in_bytes !== undefined) m.net_in_mbps = (m.net_in_bytes * 8) / 1000000
  if (m.net_out_mbps === undefined && m.net_out_bytes !== undefined) m.net_out_mbps = (m.net_out_bytes * 8) / 1000000
  return m
}
async function audit(req: FastifyRequest, action: string, resourceId: string, details: any) { await db.query(`INSERT INTO audit_logs (id,tenant_id,user_id,action,resource_type,resource_id,ip_address,details,created_at) VALUES ($1,$2,$3,$4,'host',$5,$6,$7,NOW())`, [uuid(), tenant(req), userId(req), action, resourceId, req.ip, details]).catch(() => undefined) }

export default async function hostsRoutes(fastify: FastifyInstance) {
  fastify.addHook('preHandler', (fastify as any).authenticate)
  fastify.get('/hosts', async (req, reply) => { try { const q: any = req.query || {}; const p: any[] = [tenant(req)]; let w = 'h.tenant_id=$1'; if (q.group) { p.push(q.group); w += ` AND h.host_group_id=$${p.length}` } if (q.status) { p.push(q.status); w += ` AND h.status=$${p.length}` } if (q.search) { p.push(`%${q.search}%`); w += ` AND (h.hostname ILIKE $${p.length} OR h.display_name ILIKE $${p.length} OR h.ip_address ILIKE $${p.length})` } const r = await db.query(`SELECT h.*,hg.name group_name,COALESCE(pc.count,0)::int problem_count FROM hosts h LEFT JOIN host_groups hg ON hg.id=h.host_group_id LEFT JOIN (SELECT host_id,COUNT(*) count FROM problems WHERE status IN ('active','acknowledged') GROUP BY host_id) pc ON pc.host_id=h.id WHERE ${w} ORDER BY h.hostname`, p); return { hosts: r.rows } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to list hosts' }) } })
  fastify.post('/hosts', async (req, reply) => { try { const b: any = req.body || {}; if (!b.hostname) return reply.code(400).send({ error: 'hostname is required' }); const id = uuid(); const r = await db.query(`INSERT INTO hosts (id,tenant_id,host_group_id,hostname,display_name,ip_address,os_type,os_version,agent_key,agent_version,status,last_seen,registered_at,tags,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NULL,'unknown',NULL,NOW(),$10,$11) RETURNING *`, [id, tenant(req), b.host_group_id || null, b.hostname, b.display_name || b.hostname, b.ip_address || null, b.os_type || 'unknown', b.os_version || null, agentKey(), b.tags || [], b.metadata || {}]); await audit(req, 'host.create', id, b); return reply.code(201).send({ host: r.rows[0] }) } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to create host' }) } })
  fastify.get('/hosts/:id', async (req, reply) => { try { const { id } = req.params as any; const h = await db.query(`SELECT h.*,hg.name group_name FROM hosts h LEFT JOIN host_groups hg ON hg.id=h.host_group_id WHERE h.id=$1 AND h.tenant_id=$2`, [id, tenant(req)]); if (!h.rows[0]) return reply.code(404).send({ error: 'Host not found' }); const [s,p] = await Promise.all([db.query('SELECT * FROM host_services WHERE host_id=$1 ORDER BY name', [id]), db.query(`SELECT p.*,h.hostname FROM problems p JOIN hosts h ON h.id=p.host_id WHERE p.host_id=$1 ORDER BY p.triggered_at DESC LIMIT 200`, [id])]); return { host: h.rows[0], latest_metrics: await latestMetrics(id), services: s.rows, problems: p.rows } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get host' }) } })
  fastify.put('/hosts/:id', async (req, reply) => { try { const { id } = req.params as any; const b: any = req.body || {}; const r = await db.query(`UPDATE hosts SET host_group_id=$3,hostname=$4,display_name=$5,ip_address=$6,os_type=$7,os_version=$8,tags=$9,metadata=$10 WHERE id=$1 AND tenant_id=$2 RETURNING *`, [id, tenant(req), b.host_group_id || null, b.hostname, b.display_name || b.hostname, b.ip_address || null, b.os_type || 'unknown', b.os_version || null, b.tags || [], b.metadata || {}]); if (!r.rows[0]) return reply.code(404).send({ error: 'Host not found' }); await audit(req, 'host.update', id, b); return { host: r.rows[0] } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to update host' }) } })
  fastify.delete('/hosts/:id', async (req, reply) => { try { const { id } = req.params as any; await db.query('DELETE FROM hosts WHERE id=$1 AND tenant_id=$2', [id, tenant(req)]); await audit(req, 'host.delete', id, {}); return { ok: true } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to delete host' }) } })
  fastify.post('/hosts/:id/rotate-agent-key', async (req, reply) => { try { const { id } = req.params as any; const key = agentKey(); const r = await db.query('UPDATE hosts SET agent_key=$3 WHERE id=$1 AND tenant_id=$2 RETURNING id,agent_key', [id, tenant(req), key]); if (!r.rows[0]) return reply.code(404).send({ error: 'Host not found' }); await audit(req, 'host.rotate_agent_key', id, {}); return { agent_key: key } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to rotate key' }) } })
  fastify.get('/hosts/:id/metrics/latest', async (req, reply) => { try { return { metrics: await latestMetrics((req.params as any).id) } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get latest metrics' }) } })
  fastify.get('/hosts/:id/metrics/:metric', async (req, reply) => { try { const { id, metric } = req.params as any; const q: any = req.query || {}; const range = q.range || '24h'; if (range === '1h' || range === '6h') { const r = await db.query(`SELECT collected_at t,value v FROM metric_values WHERE host_id=$1 AND metric_name=$2 AND collected_at >= NOW() - $3::interval ORDER BY collected_at`, [id, metric, rangeInterval(range)]); const vals = r.rows.map((x:any)=>Number(x.v)); return { data: r.rows.map((x:any)=>({t:new Date(x.t).toISOString(),v:Number(x.v)})), min: vals.length?Math.min(...vals):null, max: vals.length?Math.max(...vals):null, avg: vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null } } const from = new Date(Date.now() - (range === '7d' ? 7 : 1) * 86400000); const ch = await clickhouse.query({ query: `SELECT bucket AS t, avg_value AS v FROM metrics_hourly WHERE host_id={id:String} AND metric_name={metric:String} AND bucket >= {from:DateTime} ORDER BY bucket`, query_params: { id, metric, from: from.toISOString().replace('T',' ').replace('Z','') }, format: 'JSONEachRow' }); const data:any[] = await ch.json(); const vals = data.map(x=>Number(x.v)); return { data: data.map(x=>({t:new Date(x.t).toISOString(),v:Number(x.v)})), min: vals.length?Math.min(...vals):null, max: vals.length?Math.max(...vals):null, avg: vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get metric history' }) } })
  fastify.get('/hosts/:id/problems', async (req, reply) => { try { const r = await db.query(`SELECT p.*,h.hostname,EXTRACT(EPOCH FROM (COALESCE(p.resolved_at,NOW())-p.triggered_at))*1000 duration_ms FROM problems p JOIN hosts h ON h.id=p.host_id WHERE p.host_id=$1 AND p.tenant_id=$2 ORDER BY p.triggered_at DESC`, [(req.params as any).id, tenant(req)]); return { problems: r.rows } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get host problems' }) } })
  fastify.get('/hosts/:id/services', async (req, reply) => { try { const r = await db.query('SELECT * FROM host_services WHERE host_id=$1 ORDER BY name', [(req.params as any).id]); return { services: r.rows } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get services' }) } })
  fastify.get('/hosts/:id/availability', async (req, reply) => { try { const days = Number((req.query as any).days || 7); const r = await db.query(`SELECT date_trunc('day', collected_at) day, COUNT(DISTINCT date_trunc('minute', collected_at)) samples FROM metric_values WHERE host_id=$1 AND collected_at >= NOW() - $2::interval GROUP BY 1 ORDER BY 1`, [(req.params as any).id, sinceDays(days)]); return { availability: r.rows.map((x:any)=>({ day: x.day, percent: Math.min(100, Number(x.samples) / 288 * 100) })) } } catch (e) { req.log.error(e); return reply.code(500).send({ error: 'Failed to get availability' }) } })
}
