// FILE: services/auth-api/src/routes/problems.routes.ts
import { FastifyInstance, FastifyRequest } from 'fastify'
import { db } from '../db'
function tenant(req: FastifyRequest){return (req as any).user.tenant_id} function userId(req: FastifyRequest){return (req as any).user.id||(req as any).user.user_id}
export default async function problemsRoutes(fastify: FastifyInstance){
 fastify.addHook('preHandler',(fastify as any).authenticate)
 fastify.get('/problems',async(req,reply)=>{try{const q:any=req.query||{};const p:any[]=[tenant(req)];let w='p.tenant_id=$1'; if(q.status){p.push(q.status);w+=` AND p.status=$${p.length}`}else w+=` AND p.status IN ('active','acknowledged')`; if(q.severity){p.push(q.severity);w+=` AND p.severity=$${p.length}`} if(q.host_id){p.push(q.host_id);w+=` AND p.host_id=$${p.length}`} const limit=Math.min(Number(q.limit||100),500), offset=Number(q.offset||0); p.push(limit,offset); const r=await db.query(`SELECT p.*,h.hostname,h.ip_address,EXTRACT(EPOCH FROM (COALESCE(p.resolved_at,NOW())-p.triggered_at))*1000 duration_ms FROM problems p JOIN hosts h ON h.id=p.host_id WHERE ${w} ORDER BY CASE p.severity WHEN 'critical' THEN 0 ELSE 1 END,p.triggered_at DESC LIMIT $${p.length-1} OFFSET $${p.length}`,p); return {problems:r.rows}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to list problems'})}})
 fastify.post('/problems/:id/acknowledge',async(req,reply)=>{try{const r=await db.query(`UPDATE problems SET status='acknowledged',acknowledged_at=NOW(),acknowledged_by=$3 WHERE id=$1 AND tenant_id=$2 AND status='active' RETURNING *`,[(req.params as any).id,tenant(req),userId(req)]); if(!r.rows[0])return reply.code(404).send({error:'Active problem not found'}); return {problem:r.rows[0]}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to acknowledge problem'})}})
 fastify.post('/problems/:id/resolve',async(req,reply)=>{try{const r=await db.query(`UPDATE problems SET status='resolved',resolved_at=NOW() WHERE id=$1 AND tenant_id=$2 AND status IN ('active','acknowledged') RETURNING *`,[(req.params as any).id,tenant(req)]); if(!r.rows[0])return reply.code(404).send({error:'Open problem not found'}); return {problem:r.rows[0]}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to resolve problem'})}})
 fastify.get('/problems/history',async(req,reply)=>{try{const days=Number((req.query as any).days||7);const r=await db.query(`SELECT date_trunc('day',triggered_at) day,severity,COUNT(*)::int count FROM problems WHERE tenant_id=$1 AND triggered_at>=NOW()-$2::interval GROUP BY 1,2 ORDER BY 1`,[tenant(req),`${days} days`]);return {history:r.rows}}catch(e){req.log.error(e);return reply.code(500).send({error:'Failed to get problem history'})}})
}
