// FILE: apps/dashboard/app/agents/page.tsx
'use client'
import { useEffect,useState } from 'react'
import Layout from '../../components/Layout'
import DataTable from '../../components/DataTable'
import StatusBadge from '../../components/StatusBadge'
import { createHost,getHosts,rotateAgentKey } from '../../lib/api'
import { timeAgo } from '../../lib/format'
function mask(k:string){return k?`${k.slice(0,8)}********${k.slice(-4)}`:'-'}function agentState(last:string){const d=Date.now()-new Date(last||0).getTime();return d<60000?'online':d<300000?'stale':'offline'}
export default function Agents(){const[hosts,setHosts]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>({hostname:'',ip_address:'',os_type:'Linux'});const server=process.env.NEXT_PUBLIC_AGENT_URL||'http://localhost:4000';async function load(){const r=await getHosts();setHosts(r.hosts||[])}useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();await createHost(form);setShow(false);load()}return <Layout title="Agents" breadcrumbs={['Configuration','Agents']} actions={[{label:'Register New Host',onClick:()=>setShow(true),primary:true}]}><div className="panel" style={{padding:10,marginBottom:10}}><b>Agent download</b><pre className="mono">node agent.js --server {server} --key YOUR_AGENT_KEY</pre><button className="btn" onClick={()=>alert('Copy agent/index.js from the repository agent folder.')}>Download agent.js</button></div><DataTable data={hosts} columns={[{key:'hostname',header:'Host'},{key:'agent_key',header:'Agent Key',render:r=><span className="mono">{mask(r.agent_key)}</span>},{key:'agent_version',header:'Version'},{key:'last_seen',header:'Last Heartbeat',render:r=>timeAgo(r.last_seen)},{key:'status',header:'Status',render:r=><StatusBadge status={agentState(r.last_seen)}/>},{key:'cmd',header:'Install Command',render:r=><code className="mono">node agent.js --server {server} --key {r.agent_key}</code>},{key:'actions',header:'Actions',render:r=><><button className="btn" onClick={()=>navigator.clipboard.writeText(`node agent.js --server ${server} --key ${r.agent_key}`)}>Copy</button> <button className="btn" onClick={async()=>{await rotateAgentKey(r.id);load()}}>Regenerate</button></>}]} emptyMessage="No agents"/>{show&&<div style={overlay}><form className="panel" style={modal} onSubmit={save}><h2>Register Host</h2><input required className="field" placeholder="Hostname" value={form.hostname} onChange={e=>setForm({...form,hostname:e.target.value})}/><input className="field" placeholder="IP Address" value={form.ip_address} onChange={e=>setForm({...form,ip_address:e.target.value})}/><select className="field" value={form.os_type} onChange={e=>setForm({...form,os_type:e.target.value})}><option>Linux</option><option>Windows</option><option>Network</option></select><div><button className="btn btn-primary">Register</button> <button type="button" className="btn" onClick={()=>setShow(false)}>Cancel</button></div></form></div>}</Layout>}
const overlay={position:'fixed' as any,inset:0,background:'rgba(0,0,0,.25)',display:'grid',placeItems:'center',zIndex:20};const modal={width:400,padding:16,display:'grid',gap:8}
