// FILE: apps/dashboard/app/maintenance/page.tsx
'use client'
import { useEffect,useState } from 'react'
import Layout from '../../components/Layout'
import DataTable from '../../components/DataTable'
import StatusBadge from '../../components/StatusBadge'
import { createMaintenance,deleteMaintenance,getHosts,getMaintenance } from '../../lib/api'
export default function Maintenance(){const[rows,setRows]=useState<any[]>([]),[hosts,setHosts]=useState<any[]>([]),[show,setShow]=useState(false),[form,setForm]=useState<any>({name:'',description:'',start_at:'',end_at:'',host_ids:[]});async function load(){const[r,h]=await Promise.all([getMaintenance(),getHosts()]);setRows(r.windows||[]);setHosts(h.hosts||[])}useEffect(()=>{load()},[]);async function save(e:any){e.preventDefault();await createMaintenance(form);setShow(false);load()}function state(r:any){const now=Date.now(),s=new Date(r.start_at).getTime(),e=new Date(r.end_at).getTime();return now<s?'scheduled':now>e?'expired':'active'}return <Layout title="Maintenance Windows" breadcrumbs={['Alerts','Maintenance']} actions={[{label:'Create Window',onClick:()=>setShow(true),primary:true}]}><DataTable data={rows} columns={[{key:'name',header:'Name'},{key:'hosts',header:'Hosts',render:r=>r.all_hosts?'All':(r.hosts||[]).map((h:any)=>h.hostname).join(', ')},{key:'start_at',header:'Start',render:r=>new Date(r.start_at).toLocaleString()},{key:'end_at',header:'End',render:r=>new Date(r.end_at).toLocaleString()},{key:'status',header:'Status',render:r=><StatusBadge status={state(r)}/>} ,{key:'actions',header:'Actions',render:r=><button className="btn" onClick={async()=>{await deleteMaintenance(r.id);load()}}>Delete</button>}]} emptyMessage="No maintenance windows"/>{show&&<div style={overlay}><form className="panel" style={modal} onSubmit={save}><h2>Create Maintenance</h2><input required className="field" placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="field" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input required type="datetime-local" className="field" value={form.start_at} onChange={e=>setForm({...form,start_at:e.target.value})}/><input required type="datetime-local" className="field" value={form.end_at} onChange={e=>setForm({...form,end_at:e.target.value})}/><select multiple className="field" onChange={e=>setForm({...form,host_ids:Array.from(e.target.selectedOptions).map((o:any)=>o.value)})}>{hosts.map(h=><option key={h.id} value={h.id}>{h.hostname}</option>)}</select><div><button className="btn btn-primary">Save</button> <button type="button" className="btn" onClick={()=>setShow(false)}>Cancel</button></div></form></div>}</Layout>}
const overlay={position:'fixed' as any,inset:0,background:'rgba(0,0,0,.25)',display:'grid',placeItems:'center',zIndex:20};const modal={width:430,padding:16,display:'grid',gap:8}
